In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
oneDArray = np.array([1, 2, 3, 4, 5])  #NumPy Arrays
print(oneDArray)

[1 2 3 4 5]


In [4]:
print(oneDArray.ndim)   #No of dim of Numpy Arrays

1


In [6]:
print(type(oneDArray))

<class 'numpy.ndarray'>


In [7]:
print(oneDArray.dtype)

int32


In [15]:
print(oneDArray[1])     #Indexing

2


In [29]:
print(oneDArray.shape)    #Array Shape

(5,)


In [32]:
for i in oneDArray:     #iterate over OneD
    print (i)

1
2
3
4
5


In [50]:
print(oneDArray + 2)   # * for multiplication / for float // for division ** for power

[3 4 5 6 7]


In [9]:
twoDArray = np.array([[1, 2, 3], [4, 5, 6]])  #2-1, 1-2
print(twoDArray)

[[1 2 3]
 [4 5 6]]


In [10]:
print(twoDArray.ndim)    

2


In [16]:
print(twoDArray[0 , 1])      

2


In [17]:
print(twoDArray[0])

[1 2 3]


In [30]:
print(twoDArray.shape)    #(no of dim, no of element)

(2, 3)


In [36]:
for i in twoDArray:         #Iterate over twoD
    for j in i:
        print(j)

1
2
3
4
5
6


In [52]:
print(twoDArray.T)

[[1 4]
 [2 5]
 [3 6]]


In [46]:
print(twoDArray + 2)

[[3 4 5]
 [6 7 8]]


In [13]:
threeDArray = np.array([[[1, 2, 3], [-1, -2, -3]], [[4, 5, 6], [-4, -5, -6]]])  #3-1, 1-2, 2-1, 1-3
print(threeDArray)

[[[ 1  2  3]
  [-1 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]


In [14]:
print(threeDArray.ndim)

3


In [21]:
print(threeDArray[1])

[[ 4  5  6]
 [-4 -5 -6]]


In [26]:
print(threeDArray[0, 1])

[-1 -2 -3]


In [27]:
print(threeDArray[0, 1, 2])

-3


In [31]:
print(threeDArray.shape)

(2, 2, 3)


In [37]:
for i in threeDArray:          #Iterate over threeD
    for j in i:
        for k in j:
            print(k)
    


1
2
3
-1
-2
-3
4
5
6
-4
-5
-6


In [48]:
print(threeDArray + 2)

[[[ 3  4  5]
  [ 1  0 -1]]

 [[ 6  7  8]
  [-2 -3 -4]]]


In [53]:
print(threeDArray.T)

[[[ 1  4]
  [-1 -4]]

 [[ 2  5]
  [-2 -5]]

 [[ 3  6]
  [-3 -6]]]


In [43]:
zerosArray = np.zeros(10)  #Create an array with 10 zeros; works for zeros and ones
print(zerosArray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [44]:
zerosArray = zerosArray.astype(int)  #Convert to int)
print(zerosArray)

[0 0 0 0 0 0 0 0 0 0]


In [45]:
preFilledArray = np.full(10, 5)  #(Array size, value)
print(preFilledArray)

[5 5 5 5 5 5 5 5 5 5]


In [56]:
matrix1 = np.array([[1,2,3], [4,5,6], [7,8,9]])        #Element-wise operation) No of col in first mat = no of rows in sec mat   
matrix2 = np.array([[10,11,12], [13,14,15], [16,17,18]])
print(matrix1)
print(matrix2)
print(matrix1 + matrix2)
print(matrix2 - matrix1)
print(matrix2 / matrix1)
print(matrix1 / matrix2)
print(matrix1 * matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[[10.          5.5         4.        ]
 [ 3.25        2.8         2.5       ]
 [ 2.28571429  2.125       2.        ]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [63]:
matmul= np.matmul(matrix1, matrix2)    #Matix Multiplication
print(matmul)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [68]:
np.min(matrix1)    #minimum value in a matrix

1

In [69]:
np.max(matmul)    #max value in a matrix

366

In [70]:
np.sum(matmul)  #sum of all values

1944

In [71]:
np.mean(matmul)  #mean of all value

216.0

In [72]:
np.std(matrix1)  #standard deviation of all value

2.581988897471611

In [74]:
np.median(matrix2)   #median of matrix 2

14.0

In [8]:
np.random.random((2,3))

array([[0.48240805, 0.44624593, 0.37323295],
       [0.83830129, 0.41613966, 0.43831214]])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])